services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=test_user
      - DATABASE_PASSWORD=test_password
      - DATABASE_NAME=blockchain_tracker

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: blockchain_tracker
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: